#!/usr/bin/env python3
"""
gen_setup_btree.py — Generates setup_btree_Nd.lp files for use with btree_constructor.lp

Each generated file contains one integrity constraint per valid decomposition vector,
selecting the correct btree/4 fact based on the clingcon constants v0..v(n-1).

Usage:
    python3 gen_setup_btree.py <n>        # generate setup_btree_Nd.lp
    python3 gen_setup_btree.py 3 4 5      # generate for multiple dimensions

The generated file is used as:
    clingcon N -c d=4 -c v0=0 -c v1=1 -c v2=2 -c v3=0 -c v4=0 \\
        setup_btree_4d.lp btree_constructor.lp
"""

import sys
from itertools import product as iproduct


def valid_vecs(n):
    """Enumerate all valid decomposition vectors for dimension n (unique, sorted)."""
    seen = set()
    # vec[i] = count of (n-i)-dimensional sub-dynamics, i in 0..n
    # constraint: sum_i vec[i] * 2^(n-i) = 2^n
    target = 2 ** n
    max_counts = [target // (2 ** (n - i)) for i in range(n + 1)]
    for counts in iproduct(*[range(mc + 1) for mc in max_counts]):
        total = sum(counts[i] * (2 ** (n - i)) for i in range(n + 1))
        if total == target:
            key = tuple(counts)
            if key not in seen:
                seen.add(key)
                yield list(counts)


def btree_terms(vec, n):
    """
    Enumère TOUTES les formes d'arbres de décomposition pour un vecteur donné.

    Un vecteur asymétrique (ex. <0,1,2>) admet plusieurs orientations d'arbre
    distinctes (selon la répartition des feuilles entre sous-arbres gauche/droit).
    L'ancien `btree_term` glouton n'en produisait qu'une, ce qui faisait perdre
    les dynamiques réalisables uniquement sous les autres orientations.

    Retourne la liste triée et dédupliquée des chaînes btree/4.
    """
    # counts : dim de feuille -> nombre de feuilles de cette dim
    counts0 = {}
    for i, cnt in enumerate(vec):
        d = n - i
        if cnt > 0:
            counts0[d] = cnt

    def vol(counts):
        return sum(c * (2 ** d) for d, c in counts.items())

    def sub_multisets_with_vol(counts, target):
        """Tous les sous-multiensembles de `counts` de volume exact `target`."""
        dims = sorted(counts)
        ranges = [range(counts[d] + 1) for d in dims]
        for pick in iproduct(*ranges):
            chosen = {d: k for d, k in zip(dims, pick) if k > 0}
            if vol(chosen) == target:
                yield chosen

    def build(dim, counts):
        # Précondition : vol(counts) == 2**dim.
        if counts == {dim: 1}:                      # une seule feuille de dim `dim`
            return [f"btree(nil,nil,{dim},nil)"]
        half = 2 ** (dim - 1)
        out = set()
        for left in sub_multisets_with_vol(counts, half):
            right = {d: counts[d] - left.get(d, 0)
                     for d in counts if counts[d] - left.get(d, 0) > 0}
            for L in build(dim - 1, left):
                for R in build(dim - 1, right):
                    out.add(f"btree({L},{R},{dim},nil)")
        return sorted(out)

    return sorted(set(build(n, counts0)))


def guards(vec, n):
    """
    Build guard conditions: vi = vec[i] for i in 0..n-1.
    Convention: vi corresponds to vec[n-1-i] (v0 = highest dim count).
    Following setup_decomp.lp: v0 is the leftmost (highest dim).
    """
    parts = []
    for vi_idx in range(n):
        vec_idx = n - 1 - vi_idx   # vi_idx=0 -> vec[n-1], vi_idx=1 -> vec[n-2], ...
        parts.append(f"v{vi_idx} = {vec[vec_idx]}")
    return ", ".join(parts)


def generate(n):
    lines = [
        f"% setup_btree_{n}d.lp",
        f"% Selects ONE btree/4 fact per decomposition vector (first orientation only).",
        f"% Generated by gen_setup_btree.py",
        f"%",
        f"% WARNING: This file fixes one arbitrary tree orientation per vector.",
        f"% Asymmetric vectors admit multiple valid orientations; only the first is",
        f"% encoded here, so enumeration via these fixed trees is INCOMPLETE.",
        f"% Use PSBN_undercontrol_treeinsolver.lp for complete enumeration.",
        f"%",
        f"% Usage:",
        f"%   clingcon N -c d={n} -c v0=X ... -c v{n}=Y \\",
        f"%       setup_btree_{n}d.lp btree_constructor.lp",
        f"",
        f"#const d = {n}.",
    ]
    for i in range(n+1):
        lines.append(f"#const v{i} = 0.")
    lines.append("")

    vecs = list(valid_vecs(n))
    lines.append(f"% {len(vecs)} valid decomposition vectors for d={n}")
    lines.append("")

    for vec in vecs:
        terms = btree_terms(vec, n)
        guard = guards(vec, n+1)
        vec_str = ",".join(map(str, vec))
        lines.append(f"% vec = <{vec_str}>  ({len(terms)} orientation(s), only first used)")
        lines.append(f"{terms[0]} :- {guard}.")
        lines.append("")

    return "\n".join(lines)


def orientation_count(vec, n):
    """Nombre d'orientations d'arbre pour un vecteur (= nb de runs `o` a lancer)."""
    return len(btree_terms(vec, n))


if __name__ == "__main__":
    dims = [int(x) for x in sys.argv[1:]] if len(sys.argv) > 1 else [3, 4]
    for n in dims:
        content = generate(n)
        fname = f"setup_btree_{n}d.lp"
        with open(f"./{fname}", "w") as f:
            f.write(content)
        vcount = len(list(valid_vecs(n)))
        print(f"Generated {fname} ({vcount} cases)")
